---

- name: PIP | Installation
  package:
    name: "{{ pip_package_names }}"
    state: present

- name: PIP | Install asked packages
  pip:
    executable: "{{ pip_executable }}"
    name: "{{ pip_packages }}"
    state: present
